# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1

jobs:
  simplewebsite:
    docker:
      - image: yeasy/simple-web:latest
     
    steps:
      - run: echo "Hi Mom!"
  
  curltest:
    docker:
      - image: ubuntu

    steps:
      - run:
          name: Curl
          command: |
            apt update
            apt install -y curl
            curl http://localhost:80

# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
      - simplewebsite
      - curltest:
          requires:
            - simplewebsite
