# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  slack: circleci/slack@4.0

jobs:
  checkouttest:
    machine:
      image: ubuntu-2004:202008-01
      
    steps:
      - checkout
      - run: exit 1
      - slack/notify:
          event: fail
          mentions: '@here'
          template: basic_fail_1
  
  simplewebsite:
    docker:
      - image: circleci/python:3.8.0-buster
     
    steps:
      - run: echo hi
      - slack/notify:
          event: fail
          mentions: '@EngineeringTeam'
          template: basic_fail_1
      - slack/notify:
          event: pass
          branch_pattern: circleci-project-setup
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "A simple test to see if this works"
                  }
                }
              ]
            }

  notify:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - slack/notify:
          branch_pattern: circleci-project-setup
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "*This is a text notification from its own job*",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: always

# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - checkouttest:
          context: slack-secrets
      - simplewebsite:
          context: slack-secrets
      - notify:
          context: slack-secrets
