# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  slack: circleci/slack@3.4.2

jobs:
  checkouttest:
    machine:
      image: ubuntu-2004:202008-01
      
    steps:
      - checkout
      - run: exit 1
      - slack/notify:
          color: "#42e2f4"
          mentions: "${CIRCLE_USERNAME},"
          message: So this is the Checkout tests notification
      - slack/status:
          fail_only: true
          mentions: "${CIRCLE_USERNAME}"
  
  simplewebsite:
    docker:
      - image: circleci/python:3.8.0-buster
     
    steps:
      - checkout 

      - run: 
          name: Copy Results
          command: |
            mkdir -p ~/phpunit
            cp ./report.xml ~/phpunit/browsertests.xml

      - store_test_results:
          path: ~/phpunit

      - run: 
          name: Get Results
          command: |
            curl https://circleci.com/api/v1.1/project/github/lg0killer/${CIRCLE_JOB}/${CIRCLE_BUILD_NUM}/tests -H "Circle-Token: ${CIRLCE_API_KEY}"

      - slack/notify:
          color: "#42e2f4"
          mentions: "${CIRCLE_USERNAME},"
          message: A custom message to notify the channel about the latest build
      - slack/status:
          fail_only: true
          mentions: "${CIRCLE_USERNAME}"


# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - checkouttest:
          context: slack-secrets
      - simplewebsite
