# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  checkouttest:
    docker: 
      - image: circleci/python:3.8
      
    steps:
      - checkout
      - add_ssh_keys:
           fingerprints:
              - "29:0c:ac:58:11:70:b3:69:13:00:6c:9e:dc:0d:e3:83"
      - run:
          name: checkout
          command: |
            GIT_SSH_COMMAND='ssh -i ~/.ssh/id_rsa_290cac581170b36913006c9edc0de383'
            git clone git@github.com:lg0killer/HomeServer.git ../stuffs
            ls
            ls ../
          
  
  simplewebsite:
    docker:
      - image: yeasy/simple-web:latest
     
    steps:
      - run: echo "Hi Mom!"
  
  curltest:
    docker:
      - image: ubuntu
      - image: yeasy/simple-web:latest

    steps:
      - run:
          name: Curl
          command: |
            apt update
            apt install -y curl
            curl http://localhost:80

# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - checkouttest
      - simplewebsite
      - curltest:
          requires:
            - simplewebsite
