# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  checkouttest:
    machine:
      image: ubuntu-2004:202008-01
      
    steps:
      - checkout
      - add_ssh_keys:
           fingerprints:
              - "29:0c:ac:58:11:70:b3:69:13:00:6c:9e:dc:0d:e3:83"
      - run:
          name: checkout
          command: |
            git clone git@github.com:lg0killer/HomeServer.git ../stuffs
      - run:
          name: Setting up Chromium apt repo
          command: |
            sudo apt update
            sudo apt install -y gnupg
            sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys DCC9EFBF77E11517
            sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 648ACFD622F3D138
            sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 112695A0E562B32A
            sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys AA8E81B4331F7F50
            sudo add-apt-repository 'deb http://ftp.debian.org/debian buster main'
            sudo add-apt-repository 'deb http://ftp.debian.org/debian buster-updates main'
            sudo apt update
            DEBIAN_FRONTEND=noninteractive sudo apt install -y curl libzip-dev zip libnss3-dev chromium php7.4 php7.4-zip php7.4-gd php7.4-intl php7.4-xsl php7.4-mbstring php7.4-curl
            sudo curl -s https://getcomposer.org/installer | php
            sudo mv composer.phar /usr/local/bin/composer
            
      - run:
          name: Curl
          command: |
            sudo apt install net-tools
            sudo netstat -tulpn
            docker-compose up -d
            sudo apt update
            sudo apt install -y curl
            curl http://localhost:80    
  
  simplewebsite:
    docker:
      - image: circleci/python:3.8.0-buster
     
    steps:
      - run: echo hi


# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - checkouttest
      - simplewebsite
